name: Java CI-CD-Pipeline-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "module4taskinfo"
  EB_APPLICATION_NAME       : ""
  EB_ENVIRONMENT            : ""
  DEPLOY_PACKAGE_NAME       : "test_app_${{ github.sha }}.jar"
  AWS_REGION_NAME           : "eu-central-1"
  
on: 
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build  

      - name : Configure aws credentials 
        uses : aws-actions/configure-aws-credentials@v1
        with : 
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY }}  
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}

      - name: copy deployment jar-file to s3 bucket 
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Print message - CI finish
        run : echo "CI Pipeline part finished successfully"
        
        
        
        
        
        
        
        
        
        
        
        
        
   
