name: Java CI-CD-Pipeline-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "module4taskinfo"
  EB_APPLICATION_NAME       : ""
  EB_ENVIRONMENT            : ""
  DEPLOY_PACKAGE_NAME       : ""
  AWS_REGION_NAME           : "eu-central-1"
  

on: 
  push:
    branches: 
      -master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3
       
       
#       - name : Create jar file 
#         run  :  
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
   
